<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Captcha\Block\Captcha\DefaultCaptcha $block */

/** @var \Magento\Captcha\Model\DefaultModel $captcha */
$captcha = $block->getCaptchaModel();
?>
<div class="field captcha required" role="<?= $block->escapeHtmlAttr($block->getHtmlId()) ?>">
    <input name="<?= $block->escapeHtmlAttr(\Magento\Captcha\Helper\Data::INPUT_NAME_FIELD_VALUE) ?>[<?= $block->escapeHtmlAttr($block->getHtmlId()) ?>]" type="text" class="input-text required-entry" data-validate="{required:true}" id="<?= $block->escapeHtmlAttr($block->getHtmlId()) ?>" autocomplete="off"/>
    <div class="nested">
        <div class="field captcha no-label"
             data-captcha="<?= $block->escapeHtmlAttr($block->getHtmlId()) ?>"
             id="captcha-container-<?= $block->escapeHtmlAttr($block->getHtmlId()) ?>"
             data-mage-init='{"captcha":{"url": "<?= $block->escapeUrl($block->getRefreshUrl()) ?>",
                                        "imageLoader": "<?= $block->escapeUrl($block->getViewFileUrl('images/loader-2.gif')) ?>",
                                         "type": "<?= $block->escapeHtmlAttr($block->getHtmlId()) ?>"}}'>
            <div class="control captcha-image">
                <img alt="<?= $block->escapeHtmlAttr(__('Please type the letters and numbers below')) ?>" class="captcha-img" height="<?= /* @noEscape */ (float) $block->getImgHeight() ?>" src="<?= $block->escapeUrl($captcha->getImgSrc()) ?>"/>
                <button type="button" class="action reload captcha-reload" title="<?= $block->escapeHtmlAttr(__('Reload captcha')) ?>"><span><?= $block->escapeHtml(__('Reload captcha')) ?></span></button>
            </div>
        </div>
        <?php if ($captcha->isCaseSensitive()) :?>
            <div class="captcha-note note">
                <?= $block->escapeHtml(__('<strong>Attention</strong>: Captcha is case sensitive.'), ['strong']) ?>
            </div>
        <?php endif; ?>
    </div>
</div>
