<?php
/**
 * @var $block \Magezon\Builder\Block\Element
 */

$coreHelper   = $this->helper('\Magezon\Core\Helper\Data');
$elements     = $this->getElements();
$count        = count($elements);
$element      = $this->getElement();
$id           = $element->getId();
$title        = $coreHelper->filter($element->getData('title'));
$titleAlign   = $element->getData('title_align');
$titleTag     = $element->getData('title_tag');
$description  = $coreHelper->filter($element->getData('description'));
$showLine     = $element->getData('show_line');
$activeTab    = $element->hasData('active_tab') ? $element->getActiveTab() - 1 : 0;
$hideEmptyTab = $element->getData('hide_empty_tab');
$tabAlign     = $element->getData('tab_align');
$tabPosition  = $element->getData('tab_position');
$spacing      = (int) $element->getData('spacing');
$gap          = (int) $element->getData('gap');
$indicator    = $element->getData('indicator');
$navAlign     = $element->getData('nav_align');
$nextLabel    = $element->getData('next_label');
$prevLabel    = $element->getData('prev_label');
?>
<?php if ($count) { ?>
	<div class="mgz-block">
		<?php if ($title || $description) { ?>
			<div class="mgz-block-heading mgz-block-heading-align-<?= $titleAlign ?><?= $showLine ? ' mgz-block-heading-line' : '' ?>">
				<?php if ($title) { ?>
					<<?= $titleTag ?> class="title"><?= $title ?></<?= $titleTag ?>>
				<?php } ?>
				<?php if ($description) { ?>
					<p class="info"><?= $description ?></p>
				<?php } ?>
			</div>
		<?php } ?>
		<div class="mgz-block-content">
			<?php
			$tabs = [];
			foreach ($elements as $index => $_element) {
				if ($index == 0) $_element->addWrapperClasses('mgz-element-first');
				if (($index+1) == ($count-1)) $_element->addWrapperClasses('mgz-element-last');
				$_html = $_element->toHtml();
				if (!$hideEmptyTab || ($hideEmptyTab && substr_count($_html, 'mgz-element-inner') > 1)) {
					$tabs[] = [
						'element' => $_element,
						'html'    => $_html
					];
				}
			}
			?>
			<div class="mgz-tabs bfb-pages bfb-pages-indicator-<?= $indicator ?> bfb-pages-nav-<?= $navAlign ?> mgz-tabs-<?= $id ?> mgz-element-tab-align-<?= $tabAlign ?> mgz-element-tab-position-<?= $tabPosition ?>" data-indicator="<?= $indicator ?>" data-mage-init='{"Magezon_Builder/js/tabs":{}}' data-spacing="<?= $spacing ?>" data-gap="<?= $gap ?>" data-id="<?= $id ?>">
				<?php if ($indicator !== 'tabs') { ?>
					<div class="bfb-page-indicator <?= $indicator ?>"></div>
					<script id="<?= $id ?>-indicator-progress" type="text/x-magento-template" data-template="uploader">
						<span class="bfb-page-indicator-page-title"><%- data.title %></span>
						<span class="bfb-page-indicator-page-title-sep"> - </span>
						<span class="bfb-page-indicator-steps"><?= __('Step') ?>
							<span class="bfb-page-indicator-steps-current"><%- data.current %></span> <?= __('of') ?> <span class="bfb-page-indicator-steps-total"><%- data.total %></span>
						</span>
						<div class="bfb-page-indicator-page-progress-wrap">
							<div class="bfb-page-indicator-page-progress" style="width: <%- data.width %>"></div>
						</div>
					</script>
					<script id="<?= $id ?>-indicator-circles" type="text/x-magento-template" data-template="uploader">
						<div class="bfb-page-indicator-page <%- data.classes %>">
	                        <span class="bfb-page-indicator-page-number"> <%- data.index %></span>
	                        <span class="bfb-page-indicator-page-title"> <%- data.title %></span>
	                    </div>
					</script>
					<script id="<?= $id ?>-indicator-connector" type="text/x-magento-template" data-template="uploader">
						<div class="bfb-page-indicator-page <%- data.classes %>" style="width: <%- data.width %>">
							<span class="bfb-page-indicator-page-number">
								<span class="bfb-page-indicator-page-triangle"></span>
							</span>
							<span class="bfb-page-indicator-page-title"><%- data.title %></span>
						</div>
					</script>
				<?php } ?>
				<div class="mgz-tabs-nav">
					<?php foreach ($tabs as $index => $tab) { ?>
						<?php
						$_element     = $tab['element'];
						$id           = $_element->getId();
						$addIcon      = $_element->getData('show_icon');
						$iconPosition = $_element->getData('icon_position');
						$icon         = $_element->getData('icon');
						?>
						<div class="<?= $id ?> tab-<?= $id ?>-title mgz-tabs-tab-title<?= ($index===$activeTab) ? ' mgz-active' : '' ?>" data-id="tab-<?= $id ?>-title">
							<a href="#tab-<?= $id ?>" data-id="#tab-<?= $id ?>">
								<?php if ($addIcon && $icon && $iconPosition == 'left') { ?>
									<i class="<?= $icon ?>"></i>
								<?php } ?>
								<span><?= $_element->getTitle() ?></span>
								<?php if ($addIcon && $icon && $iconPosition == 'right') { ?>
									<i class="<?= $icon ?>"></i>
								<?php } ?>
							</a>
						</div>
					<?php } ?>
				</div>
				<div class="mgz-tabs-content">
					<?php foreach ($tabs as $index => $tab) { ?>
						<?php
						$_element = $tab['element'];
						$id       = $_element->getId();
						?>
						<div class="<?= $id ?> tab-<?= $id ?>-content mgz-tabs-tab-content<?= ($index===$activeTab) ? ' mgz-active' : '' ?> bfb-animated bfb-fadeInLeft" id="tab-<?= $id ?>">
							<?= $tab['html'] ?>
							<div class="bfb-nav-buttons">
								<div class="bfb-nav-buttons-inner">
									<?php if (isset($tabs[$index-1])) { ?>
										<button class="action action-prev" type="button"><?= $prevLabel ?></button>
									<?php } ?>
									<?php if (isset($tabs[$index+1])) { ?>
										<button class="action action-next" type="button"><?= $nextLabel ?></button>
									<?php } ?>
								</div>
							</div>
						</div>
					<?php } ?>
				</div>
			</div>
		</div>
	</div>
	<?php } ?>