<?php /** @var \Magento\Framework\View\Element\Template $block */?>
<?php
$helper = $this->helper(\Sparsh\QuickView\Helper\Data::class);
$isActive = $helper->getConfig('sparsh_quick_view/general/enable');
if ($isActive == 1): ?>
<script type="text/x-magento-init">
{
    "*": {
        "quickView":  { "baseUrl": "<?= /* @noEscape */ $block->getBaseUrl() ?>" },
        "compare":{},
        "ajaxWishlist":{
            "loginUrl":"<?= /* @noEscape */ $block->getUrl('customer/account/login'); ?>"
        }
    }
}
</script>
<?php endif; ?>
